ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.financeflow.ApplicationKt.module ]
    }
}

jwt {
    secret = "financeflow-secret-key-change-me"
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/api"
    realm = "Access to FinanceFlow"
}

db {
    driver = "org.postgresql.Driver"
    jdbcUrl = "jdbc:postgresql://localhost:5432/financeflow"
    user = "postgres"
    password = "RFMaJa775"
}
